# Generated by Django 2.1.5 on 2019-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190108_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, upload_to='shop/product_icons/', verbose_name=''),
        ),
    ]
